// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/declare","dojo/_base/lang","jimu/utils"],function(n,f,l){return n([],{curvedGaugeSeries:[{type:"gauge",center:["50%","60%"],startAngle:200,endAngle:-20,axisLine:{lineStyle:{color:[[.31,"#58f7f3"],[1,"#E5E5E5"]]}},axisTick:{show:!1},splitLine:{show:!1},axisLabel:{distance:-52,textStyle:{color:"#000"}},pointer:{length:"65%",width:5},itemStyle:{normal:{}},detail:{offsetCenter:[0,"60%"],textStyle:{color:"24B5CC"}},title:{show:!1},data:[{value:0}],animationEasingUpdate:"bounceOut",
animationDurationUpdate:500,animationDelayUpdate:100}],horizontalGauge:{grid:{top:"middle",height:90},xAxis:{show:!0,offset:-27,type:"value",scale:!1,interval:1,axisTick:{show:!1},axisLine:{show:!1},axisLabel:{show:!1,showMinLabel:!0,showMaxLabel:!0,textStyle:{color:"#949494",fontStyle:"normal",fontWeight:"normal",fontFamily:"Avenir Next",fontSize:12}},splitLine:{show:!1}},yAxis:{show:!1,type:"category",data:[]},series:[{name:"",type:"bar",barWidth:30,silent:!0,animation:!1,itemStyle:{normal:{color:"#E5E5E5"}},
barGap:"-100%",data:[100],z:1},{type:"bar",barWidth:30,label:{normal:{show:!0,position:"top",offset:[20,0],textStyle:{}}},data:[{value:40,label:{normal:{textStyle:{color:"#24B5CC",fontStyle:"normal",fontWeight:"normal",fontFamily:"Avenir Next",fontSize:12}}},itemStyle:{normal:{}}}],itemStyle:{normal:{color:"#24B5CC"}},z:10}]},verticalGauge:{grid:{left:"middle",width:60},yAxis:{show:!0,offset:-10,type:"value",interval:1,scale:!1,axisTick:{show:!1},axisLine:{show:!1},axisLabel:{show:!1,showMinLabel:!0,
showMaxLabel:!0,textStyle:{color:"#949494",fontStyle:"normal",fontWeight:"normal"}},splitLine:{show:!1}},xAxis:{show:!1,type:"category",data:[]},series:[{name:"",type:"bar",barWidth:30,silent:!0,animation:!1,itemStyle:{normal:{color:"#E5E5E5"}},barGap:"-100%",data:[100],z:1},{type:"bar",barWidth:30,label:{normal:{show:!0,position:"insideTopLeft",offset:[30,-15],textStyle:{}}},data:[{value:40,label:{normal:{textStyle:{color:"#24B5CC",fontStyle:"normal",fontWeight:"normal",fontFamily:"Avenir Next",
fontSize:12}}},itemStyle:{normal:{}}}],itemStyle:{normal:{color:"#24B5CC"}},z:10}]},setChart:function(a){this.chart=a},setRTL:function(a){this._isRTL=a},_settingValueStyle:function(a,b){if(b.gaugeOption&&l.isNotEmptyObject(b.gaugeOption.valueStyle)){var c=b.gaugeOption.valueStyle,d=c.textStyle,c=c.formatter;"horizontal"===b.shape||"vertical"===b.shape?(f.mixin(a.series[1].data[0].label.normal.textStyle,d),c&&(a.series[1].data[0].label.normal.formatter=c)):"curved"===b.shape&&(f.mixin(a.series[0].detail.textStyle,
d),c&&(a.series[0].detail.formatter=c))}return a},_settingLabelColor:function(a,b){var c="#000";b.gaugeOption&&b.gaugeOption.labelColor&&(c=b.gaugeOption.labelColor);"curved"===b.shape?a.series[0].axisLabel.textStyle.color=c:"horizontal"===b.shape?a.xAxis.axisLabel.textStyle.color=c:"vertical"===b.shape&&(a.yAxis.axisLabel.textStyle.color=c);return a},_settingHorizontalGauge:function(a,b){f.mixin(a,f.clone(this.horizontalGauge));a.grid={top:"middle",height:90,left:"10%",right:"10%"};b.min="undefined"!==
typeof b.min&&b.min?b.min:0;b.max="undefined"!==typeof b.max&&b.max?b.max:100;a.xAxis.max=b.max;a.xAxis.min=b.min;a.xAxis.scale=!0;a.series[0].data[0]=b.max;a=this._handleValue(a,b);b.labels&&b.labels[0]&&(a.series[1].data[0].name=b.labels[0]);a.series[1].name=b.series[0].name;a=this._settingNoCurvedGaugeColor(a,b);return a=this._handleHorizontalGaugeValueRTL(a,b)},_handleHorizontalGaugeValueRTL:function(a,b){if(!this._isRTL||"horizontal"!==b.shape)return a;a.series[1].label.normal.offset=[-20,0];
return a},_settingVerticalGauge:function(a,b){f.mixin(a,f.clone(this.verticalGauge));a.grid={left:"middle",width:60,top:"10%",bottom:"10%"};a.grid.left=this._getGridLeftOfVerticalGauge();b.min="undefined"!==typeof b.min&&b.min?b.min:0;b.max="undefined"!==typeof b.max&&b.max?b.max:100;a.yAxis.max=b.max;a.yAxis.min=b.min;a.series[0].data[0]=b.max;a=this._handleValue(a,b);b.labels&&b.labels[0]&&(a.series[1].data[0].name=b.labels[0]);a.series[1].name=b.series[0].name;a=this._settingNoCurvedGaugeColor(a,
b);return a=this._handleVerticalGaugeValueRTL(a,b)},_handleVerticalGaugeValueRTL:function(a,b){if(!this._isRTL||"vertical"!==b.shape)return a;var c=(b.series[0].data[0]+"").length-1;b.gaugeOption&&b.gaugeOption.valueStyle&&"undefined"!==typeof b.gaugeOption.valueStyle.decimalPlaces&&(c+=b.gaugeOption.valueStyle.decimalPlaces);a.series[1].label.normal.offset=[-17-9*c,-15];return a},_handleValue:function(a,b){var c;b.series[0].data[0]<=b.max?c=b.series[0].data[0]:(c=b.max,a.series[1].data[0].label.normal.formatter=
function(){return b.series[0].data[0]},a.tooltip.formatter=function(a){return'\x3cspan class\x3d"colorEl marginRight5" style\x3d"background-color:'+l.encodeHTML(a.color)+'"\x3e\x3c/span\x3e'+b.series[0].data[0]});a.series[1].data[0].value=c;return a},_settingCurvedGauge:function(a,b){a.series=f.clone(this.curvedGaugeSeries);b.min="undefined"!==typeof b.min&&b.min?b.min:0;b.max="undefined"!==typeof b.max&&b.max?b.max:100;a.series[0].min=b.min;a.series[0].max=b.max;a.series[0].axisLine.lineStyle.color[0][0]=
parseFloat(b.series[0].data[0]/b.max).toFixed(2);a.series[0].data[0].value=b.series[0].data[0];b.labels&&b.labels[0]&&(a.series[0].data[0].name=b.labels[0]);b.series[0].name&&(a.series[0].name=b.series[0].name);a.series[0].axisLine.lineStyle.width=30;return a=this._settingCurvedGaugeColor(a,b)},_settingGaugeSeries:function(a,b){if("gauge"!==b.type)return a;"horizontal"===b.shape?a=this._settingHorizontalGauge(a,b):"vertical"===b.shape?a=this._settingVerticalGauge(a,b):"curved"===b.shape&&(a=this._settingCurvedGauge(a,
b));a=this._settingGaugeLabel(a,b);a=this._settingLabelColor(a,b);return a=this._settingValueStyle(a,b)},_resetGraphic:function(a){a=this._settingGraphic(a);l.isNotEmptyObject(a,!0)&&this.chart.setOption({graphic:a})},_resetGrid:function(a){a=this._settingGridLeftOfVerticalGauge(a);l.isNotEmptyObject(a)&&this.chart.setOption({grid:a})},_settingGridLeftOfVerticalGauge:function(a){return"gauge"!==a.type||"vertical"!==a.shape?{}:{left:this._getGridLeftOfVerticalGauge(),width:60,top:"10%",bottom:"10%"}},
_settingCurvedGaugeColor:function(a,b){b.gaugeOption&&(b.gaugeOption.bgColor&&(a.series[0].axisLine.lineStyle.color[1][1]=b.gaugeOption.bgColor),b.gaugeOption.columnColor&&(a.series[0].axisLine.lineStyle.color[0][1]=b.gaugeOption.columnColor));return a},_settingNoCurvedGaugeColor:function(a,b){b.gaugeOption&&(b.gaugeOption.bgColor&&(a.series[0].itemStyle.normal.color=b.gaugeOption.bgColor),b.gaugeOption.columnColor&&(a.series[1].data[0].itemStyle.normal.color=b.gaugeOption.columnColor));return a},
_settingGraphic:function(a){var b=[];"gauge"===a.type&&a.gaugeOption&&("horizontal"===a.shape?b=this._settingHorizontalGraphic(a):"vertical"===a.shape&&(b=this._settingVerticalGraphic(a)));return b},_settingHorizontalGraphic:function(a){var b="#000";a.gaugeOption&&a.gaugeOption.labelColor&&(b=a.gaugeOption.labelColor);var c=[],d=this.chart.convertToPixel({yAxisIndex:0},0),d=parseInt(d,10),d=Number(d)+16;this.cacheCriticalValues=f.clone(this.criticalValues);this.criticalValues.forEach(f.hitch(this,
function(e){var h,g;"object"===typeof e?e.type&&(h=e.type,g=e.value):g=e;e=a.min||0;if(!(g>(a.max||100)||g<e)){e=this._getxAxisValueLeft(g);var f=6*(g.toString().length-2),m=e;0<f&&(m=e-f);h||c.push({z:10,type:"image",left:e,style:{image:require.toUrl("jimu")+"/css/images/chart/top_indicator.svg",width:10,height:10},silent:!0,top:d});c.push({z:10,type:"text",left:m,style:{text:g,fill:b,font:"normal 11px sans-serif"},silent:!0,top:d+11})}}));return c},_settingVerticalGraphic:function(a){var b="#000";
a.gaugeOption&&a.gaugeOption.labelColor&&(b=a.gaugeOption.labelColor);var c=[],d=this.chart.convertToPixel({xAxisIndex:0},0),d=parseFloat(d,10).toFixed(2),d=Number(d),e=require.toUrl("jimu")+"/css/images/chart/left_indicator.svg";this._isRTL&&(d+=40,e=require.toUrl("jimu")+"/css/images/chart/left_indicator_rtl.svg");var h=d-26;this.cacheCriticalValues=f.clone(this.criticalValues);this.criticalValues.forEach(f.hitch(this,function(d){var f,g;"object"===typeof d?d.type&&(f=d.type,g=d.value):g=d;d=h;
d=this._isRTL?h+11:h-11-6*(g.toString().length-1);var k=a.min||0;g>(a.max||100)||g<k||(k=this._getyAxisValueTop(g),k-=2,f||c.push({z:10,type:"image",left:h,style:{image:e,width:10,height:10},silent:!0,top:k}),c.push({z:10,type:"text",left:d,style:{text:g,fill:b,font:"normal 11px sans-serif"},silent:!0,top:k-2}))}));return c},_getGridLeftOfVerticalGauge:function(){return this.chart.getWidth()/2-30},_getxAxisValueLeft:function(a){a=this.chart.convertToPixel({xAxisIndex:0},a);return parseFloat(a,10)-
4},_getyAxisValueTop:function(a){a=this.chart.convertToPixel({yAxisIndex:0},a);return parseFloat(a,10)},_showSpecialLabel:function(a,b,c){var d=function(a){var b;c.forEach(function(c){"number"===typeof c&&0===c%1?b=c===a?c:b:1>c-a&&0<=c-a&&(b=c)});return b};"curved"===b.shape?a.series[0].axisLabel.formatter=d:"horizontal"===b.shape?a.xAxis.axisLabel.formatter=d:"vertical"===b.shape&&(a.yAxis.axisLabel.formatter=d);return a},_settingGaugeLabel:function(a,b){var c=b.min||0,d=b.max||100,e=[];b.gaugeOption&&
b.gaugeOption.showTargetValueLabel&&("curved"===b.shape&&(a.series[0].splitNumber=a.series[0].max,a.series[0].axisTick.splitNumber=1,a.series[0].axisTick.show=!1),b.gaugeOption.targetValue&&b.gaugeOption.targetValue.forEach(function(a){e.push(a)}));this.criticalValues=f.clone(e);b.gaugeOption&&b.gaugeOption.showDataRangeLabel&&(0>e.indexOf(c)&&(e.push(c),this.criticalValues.push({type:"min",value:c})),0>e.indexOf(d)&&(e.push(d),this.criticalValues.push({type:"max",value:d})));return"curved"===b.shape?
this._showSpecialLabel(a,b,e):a}})});