// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/_base/lang dojo/dom-style dojo/dom-geometry dojo/Evented esri/lang libs/echarts/echarts jimu/utils ./_Gauge dojo/_base/config libs/echarts/light libs/echarts/dark".split(" "),function(p,q,g,k,r,t,u,v,d,w,l){return p([q,t],{baseClass:"jimu-dijit-chart",templateString:"\x3cdiv\x3e\x3c/div\x3e",declaredClass:"jimu.dijit.chart",config:null,validConfig:{type:"column bar line pie radar funnel gauge".split(" "),common:"type title labels legend confine toolbox color theme backgroundColor scale dataZoom events series advanceOption".split(" "),
axisChart:["stack","axisPointer","hidexAxis","hideyAxis"],pie:["innerRadius","labelLine"],funnel:["min","max","funnelSort"],gauge:["shape","min","max","gaugeOption"],radar:["radarShape","indicator"]},defaultConfiguration:{series:{pieSeries:[{type:"pie",radius:[0,"70%"],labelLine:{normal:{show:!0,length:5,length2:5}},data:[]}],funnelSeries:[{type:"funnel",minSize:"0%",maxSize:"100%",sort:"descending",data:[]}]},toolboxs:{dataView:{title:"Data view",readOnly:!1},magicType:{title:{line:"switch to line",
bar:"switch to bar",stack:"switch to stack",tiled:"switch to tiled"},type:["line","bar","stack","tiled"]},restore:{title:"restore"},saveAsImage:{title:"save as image"}}},postCreate:function(){this.inherited(arguments);if(this.chartDom){var a=r.getMarginBox(this.chartDom);0===a.w&&(a.w=10);0===a.h&&(a.h=10);k.set(this.domNode,{width:a.w+"px",height:a.h+"px"})}else console.warn("No valid chart dom!"),k.set(this.domNode,{width:"10px",height:"10px"});this.gauge=new w;this.chart=v.init(this.domNode,this.config.theme||
"light");this.gauge.setChart(this.chart);this.gauge.setRTL(this._isRTL());this.setConfig()},updateConfig:function(a){return d.isNotEmptyObject(a)?(g.mixin(this.config,a),this.setConfig()):!1},setConfig:function(a){d.isNotEmptyObject(a)?this.config=a:this.config=this.config||{};if(!this._checkConfig(this.config))return!1;this._customTheme();this.clear();this.chart.setOption(this._chartFactory(this.config),!0);this._resize();return!0},_chartFactory:function(a){a=g.clone(a);var b=g.clone(this.defaultConfiguration),
c=this.option={},c=this._settingDefaultGrid(c,a),c=this._settingRenderOption(c,a),c=this._settingTitle(c,a),c=this._settingBackgroundColor(c,a),c=this._settingColor(c,a),c=this._settingToolTip(c,a);this._isAxisChart(a)?(c=this._settingAxisChartAxis(c,a),c=this._settingToolBox(c,a,b),c=this._settingSeries(c,a),c=this._settingStack(c,a),c=this._settingAxisDisplay(c,a)):this._isNoAxisChart(a)&&(c=this._settingToolBox(c,a,b,"magicType"),c=this._settingNoAxisCharts(c,a,b));c=this._settingLegend(c,a);c=
this._settingScale(c,a);c=this._handleChartRtl(c,a);c=this._avoidTitleToolBoxOverlap(c,a);c=this._pieChartAvoidLegendLabelOverLap(c,a);c=this._settingAdvanceOption(c,a);c=this._avoidAdjoiningColorSameForPie(c,a);this._bindEvents(a);return c},_avoidAdjoiningColorSameForPie:function(a,b){if("pie"!==b.type||!a.color||2>=a.color.length)return a;d.isNotEmptyObject(a.series,!0)&&a.series.forEach(g.hitch(this,function(b){var c=b.data.length;0===(c-1)%a.color.length&&(b=b.data[c-1],b.itemStyle||(b.itemStyle=
{}),b.itemStyle.normal||(b.itemStyle.normal={}),b.itemStyle.normal.color||(b.itemStyle.normal.color=a.color[1]))}));return a},_pieChartAvoidLegendLabelOverLap:function(a,b){if("pie"!==b.type)return a;var c=b.labelLine?.75:.85,e=this.chart.getHeight(),e=parseInt(e/2,10);b.legend&&(c-=.12,a.series[0].center=["50%",e-20]);a.series[0].radius[1]=100*c+"%";return a},_settingDefaultGrid:function(a,b){this._isAxisChart(b)&&(a.grid={top:20,bottom:10,left:10,right:10,containLabel:!0});return a},_settingRenderOption:function(a){a.hoverLayerThreshold=
1E3;a.progressiveThreshold=1E3;a.progressive=100;a.animationThreshold=1E3;return a},clear:function(){this.chart.clear()},resize:function(a,b){k.set(this.domNode,{width:a||"100%",height:b||"100%"});a?"string"===typeof a&&(a=Number(a.replace("px",""))):a=this.domNode.clientWidth;this.chart.resize();this._resize(a)},_resize:function(a){this.chart.setOption(this._settingFixedPosition(a));this.config.shape&&"curved"!==this.config.shape&&(this.gauge._resetGrid(this.config),this.gauge._resetGraphic(this.config))},
_settingFixedPosition:function(a){var b=this.config,c=this.option;this._isAxisChart(b)&&(c=this._settingDataZoom(c,b,a),c=this._settingGrid(c,b));"pie"===b.type&&(c=this._pieChartAvoidLegendLabelOverLap(c,b));return c},destroy:function(){this.chart.clear();d.isNotEmptyObject(this.config.events)&&this.config.events.forEach(g.hitch(this,function(a){this.chart.off(a.name)}));this.inherited(arguments)},_settingAxisDisplay:function(a,b){if(!this._isAxisChart(b))return a;a.xAxis.show=!b.hidexAxis;a.yAxis.show=
!b.hideyAxis;a.grid.containLabel=!b.hideyAxis;return a},_handleChartRtl:function(a,b){if(!this._isRTL())return a;if(this._isAxisChart(b)||"vertical"===b.shape||"horizontal"===b.shape)a.xAxis.inverse=!0,a.yAxis.position="right";return a},_settingTitle:function(a,b){b.title&&(a.title={textStyle:{fontSize:16}},a.title.text=b.title);return a},_settingColor:function(a,b){d.isNotEmptyObject(b.color)&&(a.color=b.color);return a},_settingBackgroundColor:function(a,b){b.backgroundColor&&(a.backgroundColor=
b.backgroundColor);return a},_settingToolTip:function(a,b){a.tooltip={};if(b.axisPointer){if(a.tooltip.trigger="axis","column"===b.type||"bar"===b.type)a.tooltip.axisPointer={type:"shadow"}}else a.tooltip.axisPointer={type:""};return a},_settingAxisChartAxis:function(a,b){a.xAxis={};a.yAxis={};"column"===b.type||"line"===b.type&&b.labels?(a.xAxis.data=b.labels,a.xAxis.type="category"):"bar"===b.type&&b.labels&&(a.yAxis.data=b.labels,a.yAxis.type="category");return a},_settingToolBox:function(a,b,
c,e){a.toolbox={};e||(e="");d.isNotEmptyObject(b.toolbox)&&(a.toolbox.feature={},b.toolbox.forEach(function(f){f!==e&&(b.stack&&(c.toolboxs.magicType.type=["line","bar","stack","tiled"]),a.toolbox.feature[f]=c.toolboxs[f])}));return a=this._handleToolBoxRTL(a,b)},_settingSeries:function(a,b){if(d.isNotEmptyObject(b.series))d.isNotEmptyObject(a.series)||(a.series=b.series);else return console.log("No series!"),a;b.series.forEach(g.hitch(this,function(c,e){var f="",f=c.type?c.type:b.type;c.data=c.data.map(g.hitch(this,
function(a,c){if(this._isNoAxisChart(b)){var f={};f.value=a;f.name=b.labels[c]||"";return f}return a}));a.series[e].name=c.name||"";a.series[e].type="column"===f?"bar":f;a.series[e].data=c.data}));return a},_settingNoAxisCharts:function(a,b,c){if("pie"===b.type)a=this._settingPie(a,b,c);else if("funnel"===b.type)a=this._settingFunnel(a,b,c);else if("radar"===b.type)a=this._settingRadar(a,b);else if("gauge"===b.type)return this.gauge._settingGaugeSeries(a,b);return this._settingSeries(a,b)},_settingScale:function(a,
b){if(!b.scale)return a;"bar"===b.type?a.xAxis.scale=!0:"line"===b.type||"column"===b.type?a.yAxis.scale=!0:"radar"===b.type&&(a.radar.scale=!0);return a},_settingAdvanceOption:function(a,b){b.advanceOption&&("object"===typeof b.advanceOption?g.mixin(a,b.advanceOption):"function"===typeof b.advanceOption&&b.advanceOption(a));return a},_bindEvents:function(a){d.isNotEmptyObject(a.events)&&a.events.forEach(g.hitch(this,function(a){this.chart.on(a.name,a.callback)}))},_settingLegend:function(a,b){if(!b.legend)return a;
a.legend={orient:"horizontal",x:"left",height:20,y:"bottom",data:[]};this._isAxisChart(b)||"gauge"===b.type?a.series.forEach(function(b){a.legend.data.push(b.name)}):"pie"!==b.type&&"funnel"!==b.type&&"radar"!==b.type||a.series[0].data.forEach(function(b){a.legend.data.push(b.name)});return a=this._handleLegendRTL(a,b)},_handleDataZoomStyle:function(a,b){b.showDataShadow=!1;b.realtime=!1;b.bottom=a.legend?30:"auto";return b},_showDataZoom:function(a,b,c){c=c||this.chart.getWidth();var e=b.series[0].data.length*
b.series.length,f=this._isRTL(),d=this._getaxisZeroPosition(b);c="bar"!==b.type?f?d.left:c-d.left-a.grid.right:d.top;this.showDataZoom=8>c/e;var h=c/(8*e),h=parseInt(100*h,10),h=100<h?100:h;c=[];var n="bar"===b.type?"xAxis":"yAxis",k="bar"===b.type?"yAxisIndex":"xAxisIndex",l="bar"===b.type?"width":"height";a=this._initAxisOfDataZoom(a,n);c=b.dataZoom.map(g.hitch(this,function(a){a={type:a,start:0,show:this.showDataZoom};a[k]=[0];a[l]=15;a.end=h;"xAxis"===n&&this._isRTL()&&(a.left="10");return a=
this._handleDataZoomStyle(b,a)}));a.dataZoom=c;return a},_settingDataZoom:function(a,b,c){if(!d.isNotEmptyObject(b.dataZoom))return{dataZoom:[]};b.dataZoom?a=this._showDataZoom(a,b,c):(this.showDataZoom=!1,a.dataZoom=[]);return a},_avoidTitleToolBoxOverlap:function(a,b){if("gauge"===b.type)return a;var c=10;b.title&&(c+=20);d.isNotEmptyObject(b.toolbox,!0)&&(c+=20);d.isNotEmptyObject(b.toolbox,!0)&&b.title&&(a.toolbox.top=20);this._isAxisChart(b)&&a.grid&&(a.grid.top=c);return a},_settingGrid:function(a,
b){if(!this._isAxisChart(b))return a;var c=10;b.title&&(c+=20);d.isNotEmptyObject(b.toolbox,!0)&&(c+=20);d.isNotEmptyObject(b.toolbox,!0)&&b.title&&(a.toolbox.top=20);a.grid&&(a.grid.top=c);var c=10,e=43;b.hideyAxis&&(c=20,e=63);var f=this._isRTL(),m=0,h=10;b.legend&&(m=10,h+=20);"bar"===b.type?(f?a.grid.left=this.showDataZoom?30:10:a.grid.right=this.showDataZoom?30:10,a.grid.bottom=h):a.grid.bottom=this.showDataZoom?e+m:c+m;return a},_handleLegendRTL:function(a,b){if(!b.legend)return a;var c={};
this._isRTL()?c.x="right":c.x="left";a.legend=g.mixin(a.legend,c);return a},_handleToolBoxRTL:function(a,b){if(!b.toolbox)return a;var c={top:0};this._isRTL()?c.right=0:c.left=0;a.toolbox=g.mixin(a.toolbox,c);return a},_initAxisOfDataZoom:function(a,b){a[b].type="value";a.xAxis.splitLine={show:!0,lineStyle:{type:"dashed"}};a.yAxis.splitLine={show:!0,lineStyle:{type:"dashed"}};return a},_isRTL:function(){return"ar"===l.locale||"he"===l.locale},_settingStack:function(a,b){if(!this._isAxisChart(b))return a;
a.series=a.series.map(function(a){b.stack&&(a.stack="stack","line"===b.type&&(a.areaStyle={normal:{}},a.smooth=!0));return a});return a},_settingPie:function(a,b,c){if("pie"!==b.type)return a;a.series=c.series.pieSeries;b.innerRadius&&(a.series[0].radius[0]=b.innerRadius);a.series[0].labelLine.normal.show="undefined"===typeof b.labelLine?!0:b.labelLine;return a},_settingFunnel:function(a,b,c){if("funnel"!==b.type)return a;a.series=c.series.funnelSeries;d.isNotEmptyObject(b.funnel)&&(a.series[0].min=
b.min||0,a.series[0].max=b.max||100,a.series[0].sort=b.funnelSort||"descending");return a},_settingRadar:function(a,b){var c=this;if("radar"!==b.type)return a;a.radar={nameGap:6,radius:"70%"};b.radarShape&&(a.radar.shape=b.radarShape);b.indicator?a.radar.indicator=b.indicator:console.error("No radar indicator");a.series=[{}];a.series[0].label={normal:{show:!0,formatter:function(a){return c._tryLocaleNumber(a.value)}}};var e=[];b.series[0].data.forEach(function(a,c){e[c]={tooltip:"\x3cspan\x3e"+b.labels[c]+
"\x3c/span\x3e"};a.forEach(function(a,f){e[c].tooltip+="\x3cbr/\x3e\x3cspan\x3e"+b.indicator[f].name+"\x3c/span\x3e : \x3cspan\x3e"+a+"\x3c/span\x3e"})});a.tooltip={trigger:"item",formatter:function(a){return'\x3cspan class\x3d"colorEl marginRight5" style\x3d"background-color:'+d.encodeHTML(a.color)+'"\x3e\x3c/span\x3e'+e[a.dataIndex].tooltip}};this.config.confine&&(a.tooltipconfine=!0);return a},_customTheme:function(){var a=this;d.isNotEmptyObject(this.chart._theme)||(this.chart._theme={});d.isNotEmptyObject(this.config.color)&&
(this.chart._theme.color=this.config.color);d.isNotEmptyObject(this.chart._theme.tooltip)||(this.chart._theme.tooltip={});this.config.confine&&(this.chart._theme.tooltip.confine=!0);this.chart._theme.tooltip.axisPointer={type:"cross",label:{show:!0,precision:2,formatter:function(b){return"number"===typeof b.value?(b=parseFloat(b.value).toFixed(2),a._tryLocaleNumber(b)):b.value}},lineStyle:{color:"#27727B",type:"dashed"},crossStyle:{color:"#27727B"},shadowStyle:{color:"rgba(200,200,200,0.3)"}};this.chart._theme.tooltip.formatter=
function(a){function b(a){var b='\x3cdiv class\x3d"tooltip-tr"\x3e',c='\x3cdiv class\x3d"colorEl marginRight5" style\x3d"background-color:'+d.encodeHTML(a.color)+'"\x3e\x3c/div\x3e',b=b+c;a.name&&"%00-"!==encodeURI(a.name)&&(b+="\x3cdiv\x3e"+a.name+"\x3c/div\x3e\x3cdiv\x3e : \x3c/div\x3e");b+="\x3cdiv\x3e"+e._tryLocaleNumber(a.value)+"\x3c/div\x3e";"pie"===a.seriesType&&(b+="\x3cdiv\x3e("+a.percent+"%)\x3c/div\x3e");return b+"\x3c/div\x3e"}var e=this;return function(a){var c='\x3cdiv class\x3d"tooltip-div"\x3e';
Array.isArray(a)?("%00-"!==encodeURI(a[0].seriesName)&&(c+='\x3cdiv class\x3d"tr"\x3e'+a[0].seriesName+"\x3c/div\x3e"),a.forEach(function(a){c+=b(a)})):("%00-"!==encodeURI(a.seriesName)&&(c+='\x3cdiv class\x3d"tr"\x3e'+a.seriesName+"\x3c/div\x3e"),c+=b(a));return c+="\x3c/div\x3e"}(a)}.bind(this);d.isNotEmptyObject(this.chart._theme.valueAxis)||(this.chart._theme.valueAxis={});d.isNotEmptyObject(this.chart._theme.valueAxis.axisLabel)||(this.chart._theme.valueAxis.axisLabel={});this.chart._theme.valueAxis.axisLabel.formatter=
function(a){return d.localizeNumber(a)}},_checkConfig:function(a){var b=!0;d.isNotEmptyObject(a)||(console.error("Empty config"),b=!1);if(!a.type||0>this.validConfig.type.indexOf(a.type))console.error("Invaild chart type!"),b=!1;var c=g.clone(this.validConfig),e=c.common,f=[],f="column"===a.type||"bar"===a.type||"line"===a.type?e.concat(c.axisChart):e.concat(c[a.type]);Object.keys(a).forEach(function(a){0>f.indexOf(a)&&(b=!1,console.error("Invalid configuration parameter: "+a))});return b},_tryLocaleNumber:function(a){var b=
a;if(u.isDefined(a)&&isFinite(a))try{var c=d.localizeNumber(a);"string"===typeof c&&(b=c)}catch(e){console.error(e)}return b+""},_getaxisZeroPosition:function(a){if(!this.chart)return!1;var b={},c=0,e=0;if((d.isNotEmptyObject(a.dataZoom,!0)||a.scale)&&a.series&&a.series[0]&&a.series[0].data){var f=a.series[0].data;d.isNotEmptyObject(f,!0)&&("bar"!==a.type?e=d.getMinOfArray(f):c=d.getMinOfArray(f))}if(a=this.chart.convertToPixel({xAxisIndex:0,yAxisIndex:0},[c,e]))c=a[1]-5,b.left=a[0]-5,b.top=c;return d.isNotEmptyObject(b)?
b:!1},_isAxisChart:function(a){return"column"===a.type||"bar"===a.type||"line"===a.type},_isNoAxisChart:function(a){return"pie"===a.type||"funnel"===a.type||"radar"===a.type||"gauge"===a.type}})});