// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang ./BaseDijit dojo/dom-style dojo/_base/html jimu/utils ./utils ./styleUtils jimu/LayerInfos/LayerInfos jimu/DataSourceManager".split(" "),function(g,h,k,d,b,f,e,l,m,n){return g([k],{templateString:'\x3cdiv style\x3d"height:100%;width:100%;"\x3e\x3ca data-dojo-attach-point\x3d"numberContent" class\x3d"number-content no-trim" target\x3d"_blank"\x3e\x3cdiv data-dojo-attach-point\x3d"leftIcon" class\x3d"icon"\x3e\x3c/div\x3e\x3cdiv data-dojo-attach-point\x3d"number" class\x3d"number"\x3e\x3cdiv data-dojo-attach-point\x3d"prefix" class\x3d"prefix"\x3e\x3c/div\x3e\x3cdiv class\x3d"value-content" data-dojo-attach-point\x3d"valueContent"\x3e\x3c/div\x3e\x3cdiv data-dojo-attach-point\x3d"suffix" class\x3d"suffix"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv data-dojo-attach-point\x3d"rightIcon" class\x3d"icon"\x3e\x3c/div\x3e\x3c/a\x3e\x3c/div\x3e',
baseClass:"infographic-number-dijit",type:"number",config:null,postCreate:function(){this.inherited(arguments);this.value=this.features=null;this.setConfig(this.config)},onDataSourceDataUpdate:function(a){this.features=a.features;this._updateStatisticsValue()},setDataSource:function(a){this.dataSource=a;if(a.layerId){var c=m.getInstanceSync().getLayerInfoById(a.layerId);c&&c.getLayerObject().then(h.hitch(this,function(c){this.features=e.getClientFeaturesFromMap(this.map,c,a.useSelection,a.filterByExtent);
this._updateStatisticsValue()}))}else a.frameWorkDsId&&(c=n.getInstance().getData(a.frameWorkDsId))&&(this.features=c.features,this._updateStatisticsValue())},_updateStatisticsValue:function(){this.value=this.features&&this.config.statistic&&this.dataSource?e.getSingleValueFromFeatures(this.config.statistic,this.dataSource,this.features):null;this._updateUI(this.config,this.value)},setConfig:function(a){a&&a.background&&a.background.backgroundColor?b.setStyle(this.domNode,"backgroundColor",a.background.backgroundColor):
b.setStyle(this.domNode,"backgroundColor","#FFFFFF");this.config=a;this._updateStatisticsValue()},_updateUI:function(a,c){this._cleanUI();this.config=a;this.valueContent.innerHTML=null===c?this.nls.noData:c;f.isNotEmptyObject(this.config)&&this._setValueDisplay(this.config)},_setValueDisplay:function(a){a&&(this._setBackground(a),this._setFont(a),"undefined"!==typeof this.value&&(this._setDataFormat(a),a=this._getIndicatorColor(),a.color&&this._setValueColor(a.color),a.icon&&this._setIndicatorIcon(a.icon)))},
_setIndicatorIcon:function(a){a&&("left"===a.placement||"right"===a.placement?this._setLeftRightIcon(a):"replace"===a.placement&&this._setReplaceIcon(a))},_setReplaceIcon:function(a){var c=b.create("div",{"class":"indicator-icon "+a.icon});b.empty(this.valueContent);b.place(c,this.valueContent);d.set(c,"color",a.color);d.set(c,"display","inline-flex")},_setLeftRightIcon:function(a){var c;"left"===a.placement?c=this.leftIcon:"right"===a.placement&&(c=this.rightIcon);b.addClass(c,"indicator-icon "+
a.icon);d.set(c,"color",a.color)},_getIndicatorColor:function(){var a=!1,c=!1,b=this.config.indicators;b&&((b=e.getVaildIndicator(this.value,b))&&b.valueColor&&(a=b.valueColor),b&&f.isNotEmptyObject(b.iconInfo)&&(c=b.iconInfo));return{color:a,icon:c}},_setFont:function(a){if(a&&a.font){var c={};l.font.setStyle(a.font,c);b.setStyle(this.number,c)}},_setDataFormat:function(a){if(this.value&&a&&a.dataFormat){var c=this.value,b="";a=a.dataFormat;"percentage"===a.unit?(c*=100,b="%"):"thousand"===a.unit?
(b=this.nls.thousandAbbreviation,c/=1E3):"million"===a.unit?(b=this.nls.millionAbbreviation,c/=1E6):"billion"===a.unit&&(b=this.nls.billionAbbreviation,c/=1E9);""!==a.decimalPlaces&&"undefined"!==typeof a.decimalPlaces&&(c=c.toFixed(Number(a.decimalPlaces)));this.valueContent.innerHTML=c+b;a.prefix&&(this.prefix.innerHTML=a.prefix);a.suffix&&(this.suffix.innerHTML=a.suffix)}},_cleanUI:function(){b.removeClass(this.leftIcon);b.addClass(this.leftIcon,["icon"]);b.removeClass(this.rightIcon);b.addClass(this.rightIcon,
["icon"]);this.replaceIcon&&(b.destroy(this.replaceIcon),this.replaceIcon=null);b.empty(this.valueContent);b.empty(this.prefix);b.empty(this.suffix);this._setValueColor("")},_getVaildValue:function(a){if("undefined"!==typeof a)return Number(a)},_setBackground:function(a){if(a&&a.background){a=a.background;a.backgroundColor&&b.setStyle(this.domNode,"backgroundColor",a.backgroundColor);if(a.alignment){var c=a.alignment;b.removeClass(this.domNode);b.addClass(this.domNode,"infographic-number-dijit");
c.horizontal&&b.addClass(this.domNode,"horizontal-"+c.horizontal);c.vertical&&b.addClass(this.domNode,"vertical-"+c.vertical)}a.link?b.setAttr(this.numberContent,"href",a.link):b.removeAttr(this.numberContent,"href")}},_setValueColor:function(a){d.set(this.number,"color",a)}})});