// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/_base/lang dojo/_base/array esri/geometry/geometryEngine jimu/DataSourceManager jimu/statisticsUtils".split(" "),function(k,g,h,m,n,p){return{getClientFeaturesFromMap:function(a,b,e,c){var d=[],d=e?0<b.getSelectedFeatures().length?b.getSelectedFeatures():b.graphics:b.graphics;c&&(d=this._filterFeaturesByExtent(a.extent,d));return d},listenClientFeaturesFromMap:function(a,b,e,c,d){var f=[];e&&(f.push(k(b,"selection-complete",g.hitch(this,function(){d(this.getClientFeaturesFromMap(a,
b,e,c))}))),f.push(k(b,"selection-clear",g.hitch(this,function(){d(this.getClientFeaturesFromMap(a,b,e,c))}))));c&&f.push(k(a,"extent-change",g.hitch(this,function(){0<b.graphics.length&&d(this.getClientFeaturesFromMap(a,b,e,c))})));f.push(k(b,"update-end",g.hitch(this,function(){d(this.getClientFeaturesFromMap(a,b,e,c))})));d(this.getClientFeaturesFromMap(a,b,e,c));return{remove:function(){f&&h.forEach(f,g.hitch(this,function(a){a.remove()}));f=null}}},getVaildIndicator:function(a,b,e){var c=[];
b.map(g.hitch(this,function(b){(b=this._handleOperator(b,a,e))&&c.push(b)}));if(0<c.length)return c[c.length-1]},getSingleValueFromFeatures:function(a,b,e){var c=n.getInstance(),d=0;if("Features"===a.type){if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===b.dataSourceType||"Features"===c.getDataSourceConfig(b.frameWorkDsId).type)return e.length;d=0;h.forEach(e,function(a){d+=a.attributes.count});return d}if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===b.dataSourceType||"Features"===c.getDataSourceConfig(b.frameWorkDsId).type)return this._getStatsFromFeatures(e,
a.fieldName,a.statisticsType);var f=0,l=0,d=0;h.forEach(e,function(b){var c=b.attributes[a.fieldName+"_"+a.statisticsType];switch(a.statisticsType){case "sum":f+=c;break;case "min":f=Math.min(f,c);break;case "max":f=Math.max(f,c);break;case "avg":l+=b.attributes[a.fieldName+"_sum"],d+=b.attributes.count}});"avg"===a.statisticsType&&(f=0===d?0:l/d);return f},filterFeaturesByDataSourceSetting:function(a,b,e){if(0===a.length)return[];if(b.useSelection){var c=a[0].getLayer();if(c){var d=c.getSelectedFeatures();
0<d.length&&(a=h.filter(a,function(a){return-1<d.indexOf(a)}))}}b.filterByExtent&&(a=this._filterFeaturesByExtent(e.extent,a));return a},_getStatsFromFeatures:function(a,b,e){return p.getStatisticsResultFromClientSync({featureSet:{features:a},fieldName:b,statisticTypes:[e]})[e+"Field"]},_filterFeaturesByExtent:function(a,b){var e=a.normalize();return b=h.filter(b,g.hitch(this,function(a){try{if(a.geometry){var b="point"===a.geometry.type||"multipoint"===a.geometry;return h.some(e,g.hitch(this,function(c){return b?
c.contains(a.geometry):m.intersects(c,a.geometry)}))}}catch(f){console.error(f)}return!1}))},_handleOperator:function(a,b,e){function c(a){d={};a.valueColor&&(d.valueColor=a.valueColor);a.gaugeColor&&(d.gaugeColor=a.gaugeColor);a.iconInfo&&(d.iconInfo=a.iconInfo)}var d,f=a.value.map(g.hitch(this,function(b){return a.isRatio?b/100*e:b}));"greater"===a.operator&&b>f[0]?c(a):"smaller"===a.operator&&b<f[0]?c(a):"between"===a.operator&&b>f[0]&&b<f[1]?c(a):"equal"===a.operator&&b===f[0]?c(a):"notEqual"===
a.operator&&b!==f[0]&&c(a);return d},isInteger:function(a){return"number"===typeof a&&0===a%1}}});