// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/NearMe/setting/SymbologySettings.html":'\x3cdiv\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"btnAddSymbolsNode" class\x3d"esriCTAddSymbologyBtn" title\x3d"${nls.symbologySetting.addSymbologyBtnLabel}"\x3e\r\n        \x3cspan class\x3d"esriCTAddSymbologyIcon"\x3e\x3c/span\x3e\r\n        \x3cspan class\x3d"esriCTAddSymbologyLabel"\x3e${nls.symbologySetting.addSymbologyBtnLabel}\x3c/span\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"symbologyTableAttachNode" class\x3d"esriCTAddLayerTableNode"\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare jimu/BaseWidget dojo/Evented dijit/_WidgetsInTemplateMixin dojo/text!./SymbologySettings.html jimu/dijit/SimpleTable dojo/on dojo/dom-construct dojo/_base/lang dojo/string dojo/_base/array dojo/query dijit/form/Select dijit/form/ValidationTextBox dijit/form/NumberTextBox dojo/store/Memory ./SymbolChooserPopup jimu/symbolUtils esri/symbols/jsonUtils jimu/dijit/Message jimu/LayerInfos/LayerInfos".split(" "),function(r,t,u,v,w,x,m,l,f,y,k,z,p,A,B,q,C,D,n,E,F){return r([t,u,
v],{templateString:w,baseClass:"jimu-widget-nearme-setting-symbology",_layerNameStore:null,_layerFieldStore:{},_layerValuedStore:null,_layerDetails:{},_layerInfosObj:null,constructor:function(c){f.mixin(this,c)},postMixInProperties:function(){this.nls.common={};f.mixin(this.nls.common,window.jimuNls.common)},postCreate:function(){this._layerNameStore=null;this._layerFieldStore={};this._layerValuedStore=null;this._layerDetails={};this.inherited(arguments);this._createSymbologyTable();this.own(m(this.btnAddSymbolsNode,
"click",f.hitch(this,this._addSymbolBtnClicked)));F.getInstance(this.map,this.map.webMapResponse.itemInfo).then(f.hitch(this,function(c){this._layerInfosObj=c;if(this.config.attributeSymbology&&0<Object.keys(this.config.attributeSymbology).length)for(var a in this.config.attributeSymbology)this._populateTableRows(this.config.attributeSymbology[a],a);else this._layerNameStore||this._createLayerNameStore()}))},_errorMessage:function(c){(new E({message:c})).message=c},_populateTableRows:function(c,a){k.forEach(c,
f.hitch(this,function(b){b.layerId=a;this._addLayerRow(b)}))},_createSymbologyTable:function(){this._symbologyTable=new x({fields:[{name:"field",title:this.nls.symbologySetting.layerNameTitle,type:"empty",editable:!1,width:"30%"},{name:"field1",title:this.nls.symbologySetting.fieldTitle,type:"empty",editable:!0,width:"25%"},{name:"field2",title:this.nls.symbologySetting.valuesTitle,type:"empty",editable:!1,width:"20%"},{name:"field3",title:this.nls.symbologySetting.symbolTitle,type:"empty",editable:!1,
width:"15%"},{name:"actions",title:this.nls.symbologySetting.actionsTitle,width:"10%",type:"actions",actions:["delete"]}],selectable:!1,autoHeight:!0});this._symbologyTable.placeAt(this.symbologyTableAttachNode);this._symbologyTable.startup()},_addSymbolBtnClicked:function(){!this._layerNameStore||this._layerNameStore&&0>=this._layerNameStore.data.length?this._errorMessage(this.nls.errorStrings.selectLayerErrorString):this._addLayerRow()},_addLayerRow:function(c){var a,b;a=this._symbologyTable.addRow({});
if(b=z(".simple-table-cell",a.tr))a=a.tr,this._addLayerNameDropdown(b[0],a,c),this._addLayerFieldDropdown(b[1],a,c),this._addLayerValueDropdown(b[2],a,c),this._addSymbolPicker(b[3],a,c)},_addSymbolPicker:function(c,a,b){var e={};a.symbol?e.symbol=n.fromJson(a.symbol):b&&b.symbol?e.symbol=n.fromJson(b.symbol):this.config&&this.config.symbols&&this.config.symbols.hasOwnProperty("graphicLocationSymbol")&&(e.symbol=n.fromJson(this.config.symbols.graphicLocationSymbol));var g={symbolChooserTitle:this._getFieldAlias(a),
symbolParams:e,nls:this.nls,symbolType:"graphicLocationSymbol"},d=l.create("div",{style:"height: 27px;"},c);this._showSelectedSymbol(d,e.symbol,a);this.own(m(d,"click",f.hitch(this,function(){g.symbolChooserTitle=this._getFieldAlias(a);g.symbolParams.symbol=n.fromJson(a.symbol);this._initSymbolChooserPopup(g,d,a)})))},_getFieldAlias:function(c){var a,b;a=c.layerNameDropDown.getValue();c=c.layerFieldDropDown.getValue();b="";this._layerDetails[a]&&this._layerDetails[a].fields&&this._layerDetails[a].fields[c]&&
this._layerDetails[a].fields[c].fieldAlias&&(b=this._layerDetails[a].fields[c].fieldAlias);return b},_initSymbolChooserPopup:function(c,a,b){var e=new C(c);e.onOkClick=f.hitch(this,function(){var c=e.symbolChooser.getSymbol();this._showSelectedSymbol(a,c,b);e.popup.close()})},_showSelectedSymbol:function(c,a,b){l.empty(c);var e,g,d;if(a){26<a.height&&(e=f.clone(a.height),a.height=26);26<a.width&&(g=f.clone(a.width),a.width=26);20<a.size&&(d=f.clone(a.size),a.size=20);var h=D.createSymbolNode(a);h||
(h=l.create("div"));l.place(h,c);e&&(a.height=e);g&&(a.width=g);d&&(a.size=d);b.symbol=a.toJson()}},_addLayerNameDropdown:function(c,a,b){c=l.create("div",{"class":"esriCTDropDownContainer"},c);this._layerNameStore||this._createLayerNameStore();a.layerNameDropDown=new p({name:"layerSelect",store:this._layerNameStore,labelAttr:"name","class":"esriCTLayerNameDropdown"},c);a.layerNameDropDown.startup();b&&a.layerNameDropDown.set("value",b.layerId,!1);m(a.layerNameDropDown,"change",f.hitch(this,function(){this._createLayerFieldsStore(a);
a.layerFieldDropDown.setStore(this._layerFieldStore);this._addLayerValueDropdown(a.cells[2],a,null)}));a.layerNameDropDown.startup()},_createLayerNameStore:function(c){var a;a=[];k.forEach(c||this.config.searchLayers,f.hitch(this,function(b){a.push({name:b.title,value:b.id})}));this._layerNameStore=new q({idProperty:"value",data:a})},_addLayerFieldDropdown:function(c,a,b){l.empty(c);c=l.create("div",{"class":"esriCTDropDownContainer"},c);this._createLayerFieldsStore(a);a.layerFieldDropDown=new p({name:"fieldSelect",
labelAttr:"name",store:this._layerFieldStore,"class":"esriCTLayerFieldDropDown"},c);m(a.layerFieldDropDown,"change",f.hitch(this,function(){this._addLayerValueDropdown(a.cells[2],a,null)}));b&&a.layerFieldDropDown.set("value",b.fieldName,!1);a.layerFieldDropDown.startup()},_createLayerFieldsStore:function(c){var a,b,e;a=[];b=c.layerNameDropDown.getValue();e=this._layerInfosObj.getLayerInfoById(b).layerObject;this._layerDetails[b]||(this._layerDetails[b]={fields:{}});k.forEach(e.fields,f.hitch(this,
function(c){var d,h;-1==="esriFieldTypeDate esriFieldTypeOID esriFieldTypeGeometry esriFieldTypeBlob esriFieldTypeRaster esriFieldTypeGUID esriFieldTypeXML".split(" ").indexOf(c.type)&&(d=c.name,this._layerDetails[b].fields[d]||(this._layerDetails[b].fields[d]={},this._layerDetails[b].fields[d].fieldAlias=c.alias,(h=e.getDomain(d))?(this._layerDetails[b].fields[d].codedDomainStore=this._getCodedDomainStore(h),this._layerDetails[b].fields[d].type=h.type):this._layerDetails[b].fields[d].codedDomainStore=
null),a.push({name:c.alias||c.name,value:c.name}))}));this._layerFieldStore=new q({idProperty:"value",data:a})},_getCodedDomainStore:function(c){var a;a=[];k.forEach(c.codedValues,f.hitch(this,function(b){a.push({name:b.name,value:b.code})}));return new q({idProperty:"value",data:a})},_addLayerValueDropdown:function(c,a,b){var e,f,d,h,k;l.empty(c);f=a.layerNameDropDown.getValue();d=a.layerFieldDropDown.getValue();e=l.create("div",{"class":"esriCTDropDownContainer esriCTLayerFieldDropDown"},c);c=l.create("div",
{"class":"esriCTDropDownContainer esriCTLayerFieldDropDown"},c);h=this._layerDetails[f].fields[d].codedDomainStore;k=this._layerDetails[f].fields[d];h&&"codedValue"===k.type?(a.layerValueDropDown=new p({name:"valuesSelect",labelAttr:"name",store:h,"class":"esriCTLayerValuedDropDown"},e),a.layerValueDropDown.startup(),b&&a.layerValueDropDown.set("value",b.fieldValue)):h&&"range"===k.type?(b=this._layerInfosObj.getLayerInfoById(f).layerObject,d=b.getDomain(d),a.valueTextBox=new B({"class":"esriCTLayerValuedDropDown",
constraints:{min:d.minValue,max:d.maxValue}},c),a.valueTextBox.startup()):(a.valueTextBox=new A({"class":"esriCTLayerValuedDropDown"},c),a.valueTextBox.startup(),b&&a.valueTextBox.set("value",b.fieldValue))},updateLayerOptions:function(c){var a;this._createLayerNameStore(c);k.forEach(this._symbologyTable.getRows(),f.hitch(this,function(b){b.layerNameDropDown&&0<this._layerNameStore.query({value:b.layerNameDropDown.getValue()}).length?(a=b.layerNameDropDown.getValue(),b.layerNameDropDown.setStore(this._layerNameStore),
b.layerNameDropDown.set("value",a),a!==b.layerNameDropDown.getValue()&&(b.layerFieldDropDown&&(this._createLayerFieldsStore(b),b.layerFieldDropDown.setStore(this._layerFieldStore)),this._addLayerValueDropdown(b.cells[2],b,null))):this._symbologyTable.deleteRow(b)}))},getConfig:function(){var c={},a,b,e,g=!0,d;k.forEach(this._symbologyTable.getRows(),f.hitch(this,function(d){d.layerNameDropDown&&(e=d.layerNameDropDown.getValue(),b=this._layerInfosObj.getLayerInfoById(e).layerObject,a={},a.fieldName=
d.layerFieldDropDown.getValue(),b.getDomain(a.fieldName)?a.fieldValue=d.layerValueDropDown.getValue():a.fieldValue=d.valueTextBox.getValue(),d.symbol&&(a.symbol=d.symbol),c.hasOwnProperty(e)||(c[e]=[]),k.forEach(c[e],f.hitch(this,function(b){if(b.fieldName===a.fieldName&&b.fieldValue===a.fieldValue)return g=!1,!0})),c[e].push(a))}));if(g)return{isValid:g,symbolConfig:c};d=y.substitute(this.nls.symbologySetting.invalidConfigMsg,{fieldName:a.fieldName,layerName:b.name});return{isValid:g,message:d}}})});