// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"dojo/throttle":function(){define([],function(){return function(g,f){var e=!0;return function(){e&&(e=!1,g.apply(this,arguments),setTimeout(function(){e=!0},f))}}})},"widgets/FullScreen/_build-generate_module":function(){define(["dojo/text!./Widget.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/FullScreen/Widget.html":'\x3cdiv\x3e\r\n\t\x3cdiv class\x3d"operate-item fullScreen" data-dojo-attach-event\x3d"onclick:_onFullScreenClick" data-dojo-attach-point\x3d"fullScreenBtn" title\x3d"${label}"\x3e\x3c/div\x3e\r\n\x3c/div\x3e',
"url:widgets/FullScreen/css/style.css":'.jimu-widget-fullScreen {border-radius: 4px;}.jimu-widget-fullScreen:not(.jimu-main-background) {opacity: 0.8; color: rgba(0, 0, 0, 0.8);}.jimu-widget-fullScreen:not(.jimu-main-background) .fullScreen{background-color: rgba(0,0,0,0.2);}.jimu-widget-fullScreen:hover{opacity: 1;}.jimu-widget-fullScreen .fullScreen {width: 30px; height: 30px; text-align: center; color: #fff; line-height: 30px; font-size: 14px; margin-left: auto; margin-right: auto; cursor: pointer; border-radius: 5px;}.jimu-widget-fullScreen .fullScreen:before{font-family: \'Themefont\';}.jimu-widget-fullScreen .fullScreen.restore:before {content: "\\a906";}.jimu-widget-fullScreen .fullScreen.maximize:before {content: "\\a905";}:-webkit-full-screen {width: 100%; height: 100%; background: #11ee11;}:-moz-full-screen {width: 100%; height: 100%; background: #11ee11;}:-ms-fullscreen {width: 100%; height: 100%; background: #11ee11;}:fullscreen {width: 100%; height: 100%; background: #11ee11;}:full-screen {width: 100%; height: 100%; background: #11ee11;}:fullscreen-ancestor {z-index: -1;}.body-fullscreened \x3e .dijitPopup {z-index: 2147483647 !important;}',
"*now":function(g){g(['dojo/i18n!*preload*widgets/FullScreen/nls/Widget*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])},"*noref":1}});
define("dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/on dojo/query dojo/dom-style jimu/BaseWidget dojo/throttle dojo/_base/fx dijit/focus dojo/topic dojo/_base/window jimu/PanelManager jimu/utils".split(" "),function(g,f,e,k,h,b,m,n,l,p,q,r,t,u){return g([m],{name:"FullScreen",baseClass:"jimu-widget-fullScreen",domsCache:{map:null,doc:null},ACTION:{HIDE:"hide",SHOW:"show"},MODE:{RESTORE:"restore",MAXIMIZE:"maximize"},status:{lastState:{top:0,right:0,bottom:0,left:0},_mouseX:-1,_mouseY:-1},
_timer:null,_waitMouseStopTime:2E3,_animationList:[],_animFadeTime:500,_changeColorThemes:["BillboardTheme","BoxTheme","DartTheme","PlateauTheme"],startup:function(){this.domsCache={doc:this._getDocument(),body:r.body(),map:this._getFullscreenElementByTheme()};this.status.state=this.MODE.RESTORE;e.add(this.fullScreenBtn,this.status.state);-1<this._changeColorThemes.indexOf(this.appConfig.theme.name)&&e.add(this.domNode,"jimu-main-background");this.own(k(this.domsCache.doc,"webkitfullscreenchange,mozfullscreenchange,MSFullscreenChange,fullscreenchange",
f.hitch(this,"_onFullScreenChangeEvent")));this.own(k(this.domsCache.map,"mousemove",n(f.hitch(this,this._setTimerByMouseMove),100)));this.own(q.subscribe("changeMapPosition",f.hitch(this,this._changeMapPositionHandler)))},setPosition:function(a){this.inherited(arguments);"DashboardTheme"!==window.getAppConfig().theme.name||window.appInfo.isRunInMobile||(b.set(this.domNode,"z-index",110),this.placeAt(this._getDBThemeContainer()))},onAppConfigChanged:function(a){-1<this._changeColorThemes.indexOf(a.theme.name)?
e.add(this.domNode,"jimu-main-background"):e.remove(this.domNode,"jimu-main-background")},_onFullScreenClick:function(){this._toggleFullScreen()},_onFullScreenChangeEvent:function(){!1===this._isFullScreen(this.domsCache.doc)?(this.status.state=this.MODE.RESTORE,this._toggleFullScreen(this.status.state),this._restoreDisplayAllItems()):this.status.state=this.MODE.MAXIMIZE;this._toggleBtnIcon()},_setTimerByMouseMove:function(a){if(this._isMouseMoved(a)&&(this._timer&&(this._toggleItems(this.ACTION.SHOW),
window.clearTimeout(this._timer),this._timer=null),this.status.state===this.MODE.MAXIMIZE)){this._restoreDisplayAllItems();var d=this;this._timer=window.setTimeout(function(){d._toggleItems(d.ACTION.HIDE,null)},this._waitMouseStopTime)}},_getDocument:function(){return u.isInConfigOrPreviewWindow()?window.top.document:window.document},_getFullscreenElementByTheme:function(){var a=window.getAppConfig();return a&&"DashboardTheme"===a.theme.name?this._getDBThemeContainer():this.map.container},_getDBThemeContainer:function(){var a=
null;return a=window.appInfo.isRunInMobile?h("#main-page .DashboardTheme")[0]:h(".jimu-dnd-layout")[0]},_isMouseMoved:function(a){if(a&&a.pageX&&a.pageY){if(this.status._mouseX===a.pageX&&this.status._mouseY===a.pageY)return!1;this.status._mouseX=a.pageX;this.status._mouseY=a.pageY;return!0}},_isAnyInputOnFocus:function(a){if(a===this.ACTION.HIDE){a=h("input");for(var d=0,c=a.length;d<c;d++)if(p.curNode===a[d])return!0}return!1},_changeMapPositionHandler:function(a){!a||0===a.left&&0===a.top||this.status.state!==
this.MODE.MAXIMIZE||(b.set(this.domsCache.map,"top","0px"),b.set(this.domsCache.map,"right","0px"),b.set(this.domsCache.map,"bottom","0px"),b.set(this.domsCache.map,"left","0px"))},_toggleMapPosition:function(a){this._isFullScreen(this.domsCache.doc)||a===this.MODE.RESTORE?(b.set(this.domsCache.map,"top",this.status.lastState.top),b.set(this.domsCache.map,"right",this.status.lastState.right),b.set(this.domsCache.map,"bottom",this.status.lastState.bottom),b.set(this.domsCache.map,"left",this.status.lastState.left)):
(this._getPositionEndWithPx("top"),this._getPositionEndWithPx("right"),this._getPositionEndWithPx("bottom"),this._getPositionEndWithPx("left"),b.set(this.domsCache.map,"top","0px"),b.set(this.domsCache.map,"right","0px"),b.set(this.domsCache.map,"bottom","0px"),b.set(this.domsCache.map,"left","0px"))},_getPositionEndWithPx:function(a){if(a){var d=b.get(this.domsCache.map,a);if("number"===typeof d||"string"===typeof d&&!d.endWith("px"))d+="px";this.status.lastState[a]=d}},_toggleBtnIcon:function(){e.toggle(this.fullScreenBtn,
"restore");e.toggle(this.fullScreenBtn,"maximize");e.toggle(this.domsCache.body,"body-fullscreened")},_toggleFullScreen:function(a){this._toggleMapPosition(a);this._isFullScreen(this.domsCache.doc)||a===this.MODE.RESTORE?(this._timer&&(window.clearTimeout(this._timer),this._timer=null),this._toggleItems(this.ACTION.SHOW,null),this._cancelFullScreen(this.domsCache.doc)):this._launchFullScreen(this.domsCache.map)},_toggleItems:function(a,d,c){if(!0!==this._isAnyInputOnFocus(a)||d)this._interruptAndCleanAnimationList(),
this._toggleWidgetsAndPanels(a,c),this._toggleItemsByMode(h(".jimu-widget-placeholder"),a,c),this._toggleItemsByMode(h(".jimu-widget-onscreen-icon"),a,c)},_toggleItemsByMode:function(a,d,c){for(var b=0,e=a.length;b<e;b++){var f=a[b];d===this.ACTION.SHOW?this._fadeInItem(f,c):this._fadeOutItem(f,c)}},_toggleWidgetsAndPanels:function(a,d){var c=window.getAppConfig(),b;c&&"DashboardTheme"===c.theme.name?(c=this.widgetManager.getOffPanelWidgets().filter(function(a){return"closed"!==a.state}),b=[]):(c=
this.widgetManager.getOffPanelWidgets().filter(function(a){return"closed"!==a.state}),b=t.getInstance().panels.filter(function(a){return"closed"!==a.state}));c=[].concat(c,b);a===this.ACTION.SHOW?c.forEach(function(a){this._fadeInItem(a.domNode,d)}.bind(this)):c.forEach(function(a){this._fadeOutItem(a.domNode,d)}.bind(this))},_fadeOutItem:function(a,d){var c=l.fadeOut({node:a,duration:d?1:this._animFadeTime,end:0}).play(0,!0);this.own(k(c,"End",f.hitch(this,function(){b.set(a,"display","none");b.set(a,
"opacity","")}),!0));this._addToAnimationList(c)},_fadeInItem:function(a,d){var c=d?1:this._animFadeTime;b.set(a,"display","block");c=l.fadeIn({node:a,duration:c,end:.8}).play(0,!0);this.own(k(c,"End",f.hitch(this,function(){b.set(a,"opacity","")}),!0));this._addToAnimationList(c)},_addToAnimationList:function(a){this._animationList.push(a)},_interruptAndCleanAnimationList:function(){for(var a=0,b=this._animationList.length;a<b;a++)this._animationList[a].stop(!0);this._animationList.length=0;this._animationList=
[]},_restoreDisplayAllItems:function(){this._interruptAndCleanAnimationList();this._toggleItems(this.ACTION.SHOW,!0,!0)},_isFullScreen:function(a){return!!(a.fullscreenElement||a.mozFullScreenElement||a.webkitFullscreenElement||a.msFullscreenElement)},_launchFullScreen:function(a){if(a.requestFullScreen)a.requestFullScreen();else if(a.mozRequestFullScreen)a.mozRequestFullScreen();else if(a.webkitRequestFullScreen)a.webkitRequestFullScreen();else if(a.msRequestFullscreen)a.msRequestFullscreen();else return!1},
_cancelFullScreen:function(a){if(a.exitFullscreen)a.exitFullscreen();else if(a.mozCancelFullScreen)a.mozCancelFullScreen();else if(a.webkitCancelFullScreen)a.webkitCancelFullScreen();else if(a.msExitFullscreen)a.msExitFullscreen();else return!1}})});