// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/Deferred dojo/query ./utils dijit/_TemplatedMixin dijit/_WidgetBase esri/undoManager esri/OperationBase esri/graphic esri/tasks/query esri/tasks/QueryTask esri/tasks/RelationshipQuery esri/layers/FeatureLayer esri/dijit/AttributeInspector esri/dijit/Popup esri/dijit/PopupTemplate jimu/SelectionManager jimu/ConfigManager jimu/dijit/DropdownMenu jimu/dijit/LoadingIndicator jimu/LayerInfos/LayerInfos".split(" "),
function(p,d,k,f,m,l,r,q,x,y,z,A,B,t,u,C,D,E,F,G,v,H,I,J,K){var h=p([y,x],{baseClass:"related-records-editor",templateString:"\x3cdiv\x3e\x3cdiv class\x3d'operation-box' data-dojo-attach-point\x3d'operationBox'\x3e\x3cdiv class\x3d'previos-btn feature-action' data-dojo-attach-point\x3d'previouBtn'data-dojo-attach-event\x3d'click:_onPreviouBtnClick'\x3e\x3c/div\x3e\x3cdiv class\x3d'operation-title' data-dojo-attach-point\x3d'operationTitle'\x3e\x3c/div\x3e\x3cdiv class\x3d'add-new-btn' data-dojo-attach-point\x3d'addNewBtn'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'content-box' data-dojo-attach-point\x3d'contentBox'\x3e\x3c/div\x3e\x3c/div\x3e",
editorATI:null,originalFeature:null,originalLayer:null,originalJimuLayerInfo:null,layerInfosObj:null,undoManager:null,refDomNode:null,_temporaryData:null,tableInfosParam:null,postCreate:function(){this._init();f.place(this.domNode,this.refDomNode,"after");window.isRTL?f.addClass(this.previouBtn,"icon-arrow-forward"):f.addClass(this.previouBtn,"icon-arrow-back");this.loading=(new J({hidden:!0})).placeAt(this.domNode);this._clearPage();this.showFirstPage({feature:this.originalFeature,oriJimuLayerInfo:this.originalJimuLayerInfo})},
_init:function(){this.refDomNode=this.editorATI.domNode;this.originalLayer=this.originalFeature.getLayer();this.layerInfosObj=K.getInstanceSync();this.originalJimuLayerInfo=this.layerInfosObj.getLayerOrTableInfoById(this.originalLayer.id);this.undoManager=new z;this._temporaryData={eventHandles:[],dijits:[]};this._tempPopup=new F({},f.create("div"));this._tempPopup.show()},destroy:function(){this._clearPage();this._tempPopup.destroy();this.inherited(arguments)},_getRelatedTableInfoArray:function(a){var b=
new l,c=[];a.getRelatedTableInfoArray("esriRelRoleOrigin").then(d.hitch(this,function(a){k.forEach(a,function(a){this._findTableInfoFromTableInfosParam(a)&&c.push(a)},this);b.resolve(c)}));return b},_getRelatedRecordsByQuery:function(a){var b=new l,c=new t,g=new u(a.destJimuLayerInfo.getUrl()),e=a.destJimuLayerInfo.layerObject.relationships.keyField,w=a.oriJimuLayerInfo.layerObject.objectIdField;c.where=e?e+" \x3d "+a.feature.attributes[e]:w+" \x3d "+a.feature.attributes[w];c.outFields=["*"];g.execute(c,
d.hitch(this,function(a){b.resolve(a)}));return b},_getRelatedRecordsByRelatedQuery:function(a){var b=new l,c=new C,g=this._getOriRelationshipByDestLayer(a);c.outFields=["*"];c.relationshipId=g.id;var e=a.feature.attributes[a.oriJimuLayerInfo.layerObject.objectIdField];c.objectIds=[e];a.oriJimuLayerInfo.layerObject.queryRelatedFeatures(c,d.hitch(this,function(a){(a=a[e]&&a[e].features)?b.resolve(a):b.resolve([])}),d.hitch(this,function(){b.resolve([])}));return b},_getOriRelationshipByDestLayer:function(a){var b=
null;k.some(a.oriJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.destJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_getDestRelationshipByDestLayer:function(a){var b=null;k.some(a.destJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.oriJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_createATI:function(a){var b=null,c=this._findTableInfoFromTableInfosParam(a.destJimuLayerInfo);c&&(b=new h.ATI({layerInfos:[c],
hideNavButtons:!0},f.create("div")),b.startup(),this._temporaryData.dijits.push(b));c=m(b,"delete",d.hitch(this,this._onDeleteBtnClick,a));this._temporaryData.eventHandles.push(c);c=m(b,"attribute-change",d.hitch(this,this._onAttributeChange,a));this._temporaryData.eventHandles.push(c);return b},_findTableInfoFromTableInfosParam:function(a){var b=null;k.some(this.tableInfosParam,function(c){if(c.featureLayer.id===a.id)return b=c,!0},this);return b},_addNewRelatedRecord:function(a){var b=new l,c=a.destJimuLayerInfo.layerObject,
g=this._getTemplateFromLayerObject(c),g=d.mixin({},g?g.prototype.attributes:{}),e=this._getOriRelationshipByDestLayer(a),f=this._getDestRelationshipByDestLayer(a);e.keyField&&f&&f.keyField?(e=q.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,e.keyField),f=q.ignoreCaseToGetFieldKey(a.destJimuLayerInfo.layerObject,f.keyField),e&&f&&(g[f]=a.feature.attributes[e])):e.keyField&&(e=q.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,e.keyField))&&(g[e]=a.feature.attributes[e]);var h=new B(null,
null,g,null);c.applyEdits([h],null,null,d.hitch(this,function(a){var e=a[0];if(e.success&&e.objectId){a=new t;var g=new u(c.url);a.where=c.objectIdField+" \x3d "+e.objectId;a.outFields=["*"];g.execute(a,d.hitch(this,function(a){(a=a.features[0])?b.resolve(a):(h.attributes[c.objectIdField]=e.objectId,b.resolve(h))}),d.hitch(this,function(){b.reject()}))}else b.reject()}),d.hitch(this,function(){b.reject()}));return b},_deleteRelatedRecord:function(a){var b=new l;a.destJimuLayerInfo.layerObject.applyEdits(null,
null,[a.relatedFeature],d.hitch(this,function(){b.resolve()}),d.hitch(this,function(){b.reject()}));return b},_updateRelatedRecord:function(a,b){var c=new l,g=a.destJimuLayerInfo.layerObject,e=a.relatedFeature;e.attributes[b.fieldName]=b.fieldValue;g.applyEdits(null,[e],null,d.hitch(this,function(){c.resolve()}),d.hitch(this,function(){c.reject()}));return c},_getDisplayTitleOfRelatedRecord:function(a,b,c){var d=a.getInfoTemplate();return(a="popupTitle"===c&&d?"function"===typeof d.title?d.title(b):
d.title:this._getDisplayTitleFromPopup(a,b,c))?a:""},_getDisplayTitleFromPopup:function(a,b,c){(a=this._getPopupTemplateWithOnlyDisplayField(a,c))?(b.setInfoTemplate(a),this._tempPopup.setFeatures([b]),c=(c=r("td.attrValue",this._tempPopup.domNode)[0])&&c.innerHTML,b.setInfoTemplate(null)):c=q.getAttrByFieldKey(b,c);return c},_getPopupTemplateWithOnlyDisplayField:function(a,b){var c=a._getCustomPopupInfo(a.layerObject,[b]);return new G(c)},_getTemplateFromLayerObject:function(a){var b=null;a.templates&&
a.templates[0]?b=a.templates[0]:a.types&&a.types[0]&&a.types[0].templates[0]&&(b=a.types[0].templates[0]);return b},showRelatedRecords:function(a){this._changeRefDomNode();var b=d.getObject("_wabProperties.originalLayerName",!1,a.destJimuLayerInfo.layerObject)||a.destJimuLayerInfo.title;this._setOperationTitle(b);this._clearPage();this.loading.show();this._getRelatedRecordsByRelatedQuery(a).then(d.hitch(this,function(b){this._showAddNewBtn(a);0<b.length?this._setTitle(window.jimuNls.popup.relatedRecords):
this._setTitle(window.jimuNls.popup.noRelatedRecotds,"font-normal");var c=this._showFieldSelector(a.destJimuLayerInfo);k.forEach(b,function(b,g){b._layer=a.destJimuLayerInfo.layerObject;var e=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,b,c),e=f.create("div",{"class":"item record-item "+(0===g%2?"oddLine":"evenLine"),innerHTML:e},this.contentBox);e.relatedRecord=b;e=m(e,"click",d.hitch(this,function(){this._addOperation(h.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,
a.oriJimuLayerInfo,a.destJimuLayerInfo,b))}));this._temporaryData.eventHandles.push(e)},this);this.loading.hide()}))},showInspector:function(a){this._changeRefDomNode();var b=a.destJimuLayerInfo.layerObject,c=d.getObject("_wabProperties.originalLayerName",!1,b)||a.destJimuLayerInfo.title,b=d.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,b),g=this._getDisplayTitleOfRelatedRecord(a.destJimuLayerInfo,a.relatedFeature,b);"popupTitle"!==b&&(g=c+": "+g);this._setOperationTitle(g);
this._clearPage();this.loading.show();(c=this._createATI(a))&&f.place(c.domNode,this.contentBox);c=a.destJimuLayerInfo.layerObject.objectIdField;b=new t;b.where=c+" \x3d "+a.relatedFeature.attributes[c];a.destJimuLayerInfo.layerObject.selectFeatures(b,D.SELECTION_NEW,d.hitch(this,function(){this.loading.hide();var b=a.destJimuLayerInfo.layerObject.getSelectedFeatures();b&&b[0]&&b[0].geometry&&this._activeGraphicEdit(b[0],a.oriJimuLayerInfo)}));this.showRelatedTables(this._createOperationData(a.relatedFeature,
a.destJimuLayerInfo,null,null),a)},showRelatedTables:function(a,b){this._getRelatedTableInfoArray(a.oriJimuLayerInfo).then(d.hitch(this,function(c){0<c.length&&this._setTitle(window.jimuNls.popup.relatedTables);k.forEach(c,function(c,e){var g=f.create("div",{"class":"item table-item "+(0===e%2?"oddLine":"evenLine"),innerHTML:c.title},this.contentBox),g=m(g,"click",d.hitch(this,function(){c.getLayerObject().then(d.hitch(this,function(){b?this._addOperation(h.OPERATION_SHOW_INSPECTOR,b):this._addOperation(h.OPERATION_FIRST,
a);this.showRelatedRecords(this._createOperationData(a.feature,a.oriJimuLayerInfo,c,null))}))}));this._temporaryData.eventHandles.push(g)},this)}))},showFirstPage:function(a,b){this._clearPage();this._revertRefDomNode();this.showRelatedTables(a);b&&(k.forEach(this._editWidget._jimuLayerInfos.getLayerInfoArray(),function(a){a.layerObject&&a.layerObject.clearSelection&&a.id!==this.originalJimuLayerInfo.id&&v.getInstance().clearSelection(a.layerObject)},this),this.originalFeature.setSymbol(this.originalLayer.getSelectionSymbol()),
this._activeGraphicEdit(this.originalFeature))},_activeGraphicEdit:function(a,b){b&&(b.id===this.originalJimuLayerInfo.id?this.originalFeature.setSymbol(null,!0):v.getInstance().clearSelection(b.layerObject));var c;this._editWidget.editor._editVertices=!0;this._editWidget.editor._activateEditToolbar(a);a.geometry&&(c="point"===a.geometry.type?a.geometry:a.geometry.getExtent().getCenter());this._editWidget.map.infoWindow.show(c)},_onAddNewBtnClick:function(a){this.loading.show();this._addNewRelatedRecord(a).then(d.hitch(this,
function(b){this.loading.hide();this._addOperation(h.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b))}),d.hitch(this,function(){this.loading.hide()}))},_onDeleteBtnClick:function(a){this.loading.show();this._deleteRelatedRecord(a).then(d.hitch(this,function(){this.loading.hide();this._onPreviouBtnClick()}),d.hitch(this,function(){this.loading.hide()}))},_onAttributeChange:function(a,b){this.loading.show();this._updateRelatedRecord(a,
b).then(d.hitch(this,function(){this.loading.hide()}),d.hitch(this,function(){this.loading.hide()}))},_createOperationData:function(a,b,c,d){return{feature:a,oriJimuLayerInfo:b,destJimuLayerInfo:c,relatedFeature:d}},_addOperation:function(a,b){this.undoManager.add(new h.Operation(a,b,this))},_onPreviouBtnClick:function(){this.undoManager.undo()},_clearPage:function(){f.empty(this.contentBox);f.setStyle(this.addNewBtn,"display","none");k.forEach(this._temporaryData.eventHandles,function(a){a&&a.remove&&
a.remove()},this);this._temporaryData.eventHandles=[];k.forEach(this._temporaryData.dijits,function(a){a&&a.destroy&&a.destroy()},this);this._temporaryData.dijits=[]},_changeRefDomNode:function(){f.setStyle(this.refDomNode,"display","none");f.setStyle(this.operationBox,"display","block");f.addClass(this.domNode,"fix-height-mode");this.previouBtn.title=window.jimuNls.common.back;this.addNewBtn.title=window.jimuNls.common.newText;this.undoManager.peekUndo()?f.setStyle(this.previouBtn,"display","block"):
f.setStyle(this.previouBtn,"display","none")},_revertRefDomNode:function(){f.setStyle(this.refDomNode,"display","block");f.setStyle(this.operationBox,"display","none");f.removeClass(this.domNode,"fix-height-mode")},_showAddNewBtn:function(a){var b=a.destJimuLayerInfo.layerObject;"Table"===b.type&&b.getEditCapabilities&&b.getEditCapabilities().canCreate&&(f.setStyle(this.addNewBtn,"display","block"),a=m(this.addNewBtn,"click",d.hitch(this,this._onAddNewBtnClick,a)),this._temporaryData.eventHandles.push(a))},
_setTitle:function(a,b){a&&f.create("div",{"class":"title-box "+(b?b:""),innerHTML:a},this.contentBox)},_setOperationTitle:function(a){f.setAttr(this.operationTitle,"innerHTML",a);f.setAttr(this.operationTitle,"title",a)},_showFieldSelector:function(a){var b="objecid",c=r(".title-box",this.contentBox)[0],f=a.layerObject,e=[];if(!c||!a)return b;var h=a.getPopupInfo();h&&h.title&&e.push({label:window.jimuNls.popup.saveAsPopupTitle,value:"popupTitle"});k.forEach(f.fields,function(a){"globalid"!==a.name.toLowerCase()&&
"shape"!==a.name.toLowerCase()&&e.push({label:a.alias||a.name,value:a.name})});c=(new I({items:e})).placeAt(c);c.domNode.title=window.jimuNls.popup.chooseFieldTip;var l=d.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,f),n=q.ignoreCaseToGetFieldObject(a.layerObject,a.layerObject.displayField||a.layerObject.objectIdField),p=H.getInstance().getAppConfig();l?b=l:"2.3"===p.configWabVersion&&n&&n.name?b=n.name:h&&h.title?b="popupTitle":n&&n.name?b=n.name:0<e.length&&(b=e[0].value);
b&&(c.setHighlightValue(b),d.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,f));this._temporaryData.dijits.push(c);a=m(c,"click-item",d.hitch(this,function(a,b){r(".item.record-item",this.contentBox).forEach(d.hitch(this,function(c){d.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,f);var e=this._getDisplayTitleOfRelatedRecord(a,c.relatedRecord,b);c.innerHTML=e}))},a));this._temporaryData.eventHandles.push(a);return b}});h.Operation=p([A],{constructor:function(a,
b,c){this.operationName=a;this.operationData=b;this.relatedRecordsEditor=c},performUndo:function(){switch(this.operationName){case h.OPERATION_SHOW_RELATED_TABLES:return this.relatedRecordsEditor.showRelatedTables(this.operationData);case h.OPERATION_SHOW_RELATED_RECORDS:return this.relatedRecordsEditor.showRelatedRecords(this.operationData);case h.OPERATION_SHOW_INSPECTOR:return this.relatedRecordsEditor.showInspector(this.operationData);default:return this.relatedRecordsEditor.showFirstPage(this.operationData,
!0)}}});h.ATI=p([E],{constructor:function(){this._aiConnects=[];this._selection=[];this._toolTips=[]}});d.mixin(h,{OPERATION_SHOW_RELATED_TABLES:"showRelatedTables",OPERATION_SHOW_RELATED_RECORDS:"showRelatedRecords",OPERATION_SHOW_INSPECTOR:"showInspector",OPERATION_FIRST:"first"});return h});