// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/LayerList/LayerListView.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"layer-list-operations" data-dojo-attach-point\x3d"layerListOperations"\x3e\r\n    \x3c!--div class\x3d"setting-image jimu-icon jimu-icon-setting jimu-state-disabled"\x3e\x3c/div--\x3e\r\n  \x3c/div\x3e\r\n  \x3ctable class\x3d"layer-list-table"\x3e\r\n    \x3ctbody class\x3d"layers-list-body" data-dojo-attach-point\x3d"layerListTable"\x3e\x3c/tbody\x3e\r\n    \x3ctbody class\x3d"layers-list-body" data-dojo-attach-point\x3d"tableListTable"\x3e\x3c/tbody\x3e       \r\n  \x3c/table\x3e\r\n\x3c/div\x3e\r\n'}});
define("dijit/_WidgetBase dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/on dojo/query jimu/dijit/CheckBox jimu/dijit/DropMenu ./PopupMenu dijit/_TemplatedMixin dojo/text!./LayerListView.html dojo/dom-class dojo/dom-style ./NlsStrings".split(" "),function(t,u,m,k,g,n,h,v,w,x,y,z,l,p,A){return u([t,y],{templateString:z,_currentSelectedLayerRowNode:null,operationsDropMenu:null,_layerNodeHandles:null,postMixInProperties:function(){this.inherited(arguments);this.nls=A.value;
this._layerNodeHandles={}},postCreate:function(){k.forEach(this.operLayerInfos.getLayerInfoArray(),function(a){this.drawListNode(a,0,this.layerListTable)},this);k.forEach(this.operLayerInfos.getTableInfoArray(),function(a){this.drawListNode(a,0,this.tableListTable)},this);this._initOperations()},drawListNode:function(a,b,c,e){var d;this.isLayerHiddenInWidget(a)||(0===a.newSubLayers.length?(d=this.addLayerNode(a,b,c,e),this.config.showLegend?this.addLegendNode(a,b,d.subNode):(a=h(".showLegend-div",
d.currentNode)[0])&&l.add(a,"hidden")):(d=this.addLayerNode(a,b,c,e),k.forEach(a.newSubLayers,m.hitch(this,function(a,b){this.drawListNode(b,a+1,d.subNode)},b))))},addLayerNode:function(a,b,c,e){var d,f,h,k,l,r,q=a.getRootLayerInfo();this._layerNodeHandles[q.id]||(this._layerNodeHandles[q.id]=[]);d=g.create("tr",{"class":"jimu-widget-row layer-row  layer-tr-node-"+a.id,layerTrNodeId:a.id});g.place(d,c,e);f=g.create("td",{"class":"col col1"},d);for(k=0;k<b;k++)g.create("div",{"class":"begin-blank-div jimu-float-leading",
innerHTML:""},f);r=g.create("div",{"class":"showLegend-div jimu-float-leading",imageShowLegendDivId:a.id},f);h=g.create("div",{"class":"div-select jimu-float-leading"},f);k=new v({checked:a.isVisible(),"class":"visible-checkbox-"+a.id});g.place(k.domNode,h);l=g.create("div",{"class":"noLegend-div jimu-float-leading"},f);g.create("img",{"class":"noLegend-image",src:this.layerListWidget.folderUrl+(a.isTable?"images/table.png":"images/noLegend.png"),alt:"l"},l);if(a.noLegend||a.isTable)p.set(r,"display",
"none"),p.set(h,"display","none"),p.set(l,"display","block");p.set(f,"width",12*b+40+"px");b=g.create("td",{"class":"col col2"},d);f="";try{a.isInScale()||(f="grayed-title")}catch(B){console.warn(B.message)}g.create("div",{innerHTML:a.title,"class":"layer-title-div-"+a.id+" div-content jimu-float-leading "+f},b);f=g.create("td",{"class":"col col3"},d);h=this.hasContentMenu()?"display: block":"display: none";f=g.create("div",{"class":"layers-list-popupMenu-div",style:h},f);h=g.create("tr",{"class":"",
layerContentTrNodeId:a.id});g.place(h,c,e);c=g.create("td",{"class":"",colspan:"3"},h);c=g.create("table",{"class":"layer-sub-node",subNodeId:a.id},c);e=this.own(n(b,"click",m.hitch(this,this._onRowTrClick,a,r,d,c)));this._layerNodeHandles[q.id].push(e[0]);e=this.own(n(r,"click",m.hitch(this,this._onRowTrClick,a,r,d,c)));this._layerNodeHandles[q.id].push(e[0]);e=this.own(n(d,"mouseover",m.hitch(this,this._onLayerNodeMouseover,d,void 0)));this._layerNodeHandles[q.id].push(e[0]);e=this.own(n(d,"mouseout",
m.hitch(this,this._onLayerNodeMouseout,d,void 0)));this._layerNodeHandles[q.id].push(e[0]);e=this.own(n(k.domNode,"click",m.hitch(this,this._onCkSelectNodeClick,a,k)));this._layerNodeHandles[q.id].push(e[0]);e=this.own(n(f,"click",m.hitch(this,this._onPopupMenuClick,a,f,d)));this._layerNodeHandles[q.id].push(e[0]);return{currentNode:d,subNode:c}},hasContentMenu:function(){var a=!1,b;if(this.config.contextMenu)for(b in this.config.contextMenu)this.config.contextMenu.hasOwnProperty(b)&&"function"!==
typeof this.config.contextMenu[b]&&(a=a||this.config.contextMenu[b]);else a=!0;return a},destroyLayerTrNode:function(a){var b=h("[class~\x3d'layer-tr-node-"+a.id+"']",this.domNode)[0],c=h("[layercontenttrnodeid\x3d'"+a.id+"']",this.domNode)[0];b&&(a=a.getRootLayerInfo(),k.forEach(this._layerNodeHandles[a.id],function(a){a.remove()},this),delete this._layerNodeHandles[a.id],g.destroy(b),c&&g.destroy(c))},addLegendNode:function(a,b,c){c=g.create("tr",{"class":"legend-node-tr"},c);c=g.create("td",{"class":"legend-node-td"},
c);try{var e=a.createLegendsNode();p.set(e,"font-size",12*(b+1)+"px");g.place(e,c)}catch(d){console.error(d)}},_foldSwitch:function(a,b,c){return"none"===p.get(c,"display")?this._foldOrUnfoldLayer(a,!1,b,c):this._foldOrUnfoldLayer(a,!0,b,c)},_foldOrUnfoldLayer:function(a,b,c,e){var d=d?c:h("div[imageShowLegendDivId\x3d'"+a.id+"']",this.layerListTable)[0],f=f?e:h("table[subNodeId\x3d'"+a.id+"']",this.layerListTable)[0];c=null;d&&f&&(b?(p.set(f,"display","none"),l.remove(d,"unfold"),c=!0):(p.set(f,
"display","table"),l.add(d,"unfold"),c=!1,a.isLeaf()&&(b=h(".legends-div",f)[0],d=h(".legends-loading-img",b)[0],b&&d&&a.drawLegends(b,this.layerListWidget.appConfig.portalUrl))));return c},redrawLegends:function(a){var b=h("div[legendsDivId\x3d'"+a.id+"']",this.layerListTable)[0];b&&(b._legendDijit&&b._legendDijit.destroy&&b._legendDijit.destroy(),a.drawLegends(b,this.layerListWidget.appConfig.portalUrl))},_foldOrUnfoldLayers:function(a,b){k.forEach(a,function(a){this._foldOrUnfoldLayer(a,b)},this)},
_onCkSelectNodeClick:function(a,b,c){c.ctrlKey||c.metaKey?a.isRootLayer()?this.turnAllRootLayers(b.checked):this.turnAllSameLevelLayers(a,b.checked):(this.layerListWidget._denyLayerInfosIsVisibleChangedResponseOneTime=!0,a.setTopLayerVisible(b.checked));c.stopPropagation()},_onPopupMenuClick:function(a,b,c,e){var d=a.getRootLayerInfo(),f=b.popupMenu;f||(f=(new x({_layerInfo:a,box:this.layerListWidget.domNode.parentNode,popupMenuNode:b,layerListWidget:this.layerListWidget,_config:this.config})).placeAt(b),
b.popupMenu=f,a=this.own(n(f,"onMenuClick",m.hitch(this,this._onPopupMenuItemClick,a,f))),this._layerNodeHandles[d.id].push(a[0]));this._changeSelectedLayerRow(c);f&&"opened"===f.state?f.closeDropMenu():(this._hideCurrentPopupMenu(),f&&(this.currentPopupMenu=f,f.openDropMenu()));this.operationsDropMenu&&"opened"===this.operationsDropMenu.state&&this.operationsDropMenu.closeDropMenu();e.stopPropagation()},_hideCurrentPopupMenu:function(){this.currentPopupMenu&&"opened"===this.currentPopupMenu.state&&
this.currentPopupMenu.closeDropMenu()},_onLayerNodeMouseover:function(a){l.add(a,"layer-row-mouseover")},_onLayerNodeMouseout:function(a){l.remove(a,"layer-row-mouseover")},_onLayerListWidgetPaneClick:function(){this.operationsDropMenu&&this.operationsDropMenu.closeDropMenu()},_onRowTrClick:function(a,b,c,e,d){this._changeSelectedLayerRow(c);b=this._foldSwitch(a,b,e);if(d.ctrlKey||d.metaKey)a.isRootLayer()?this.foldOrUnfoldAllRootLayers(b):this.foldOrUnfoldSameLevelLayers(a,b)},_changeSelectedLayerRow:function(a){this._currentSelectedLayerRowNode&&
this._currentSelectedLayerRowNode===a||(this._currentSelectedLayerRowNode&&l.remove(this._currentSelectedLayerRowNode,"jimu-widget-row-selected"),l.add(a,"jimu-widget-row-selected"),this._currentSelectedLayerRowNode=a)},_onPopupMenuItemClick:function(a,b,c,e){e={itemKey:c.key,extraData:e,layerListWidget:this.layerListWidget,layerListView:this};"transparency"===c.key?"none"===p.get(b.transparencyDiv,"display")?b.showTransNode(a.getOpacity()):b.hideTransNode():(a=b.popupMenuInfo.onPopupMenuClick(e),
a.closeMenu&&b.closeDropMenu())},_exchangeLayerTrNode:function(a,b){var c=h("tr[layerTrNodeId\x3d'"+a.id+"']",this.layerListTable)[0],e=h("tr[layerTrNodeId\x3d'"+b.id+"']",this.layerListTable)[0],d=h("tr[layerContentTrNodeId\x3d'"+b.id+"']",this.layerListTable)[0];c&&e&&d&&(this.layerListTable.removeChild(e),this.layerListTable.insertBefore(e,c),this.layerListTable.removeChild(d),this.layerListTable.insertBefore(d,c))},_getMovedSteps:function(a,b){var c=1,e,d=this.operLayerInfos.getLayerInfoArray();
k.forEach(d,function(b,c){a.id===b.id&&(e=c)},this);if("moveup"===b)for(;!d[e].isFirst;)if(e--,this.isLayerHiddenInWidget(d[e])&&!d[e].isFirst)c++;else break;else for(;!d[e].isLast;)if(e++,this.isLayerHiddenInWidget(d[e])&&!d[e].isLast)c++;else break;return c},_initOperations:function(){this.operationsDropMenu=(new w({items:[{key:"turnAllLayersOn",label:this.nls.turnAllLayersOn},{key:"turnAllLayersOff",label:this.nls.turnAllLayersOff},{key:"separator"},{key:"expandAllLayers",label:this.nls.expandAllLayers},
{key:"collapseAlllayers",label:this.nls.collapseAlllayers}],box:this.layerListWidget.domNode.parentNode})).placeAt(this.layerListOperations);var a=h("div.jimu-dropmenu \x3e div:first-child",this.layerListOperations)[0];a&&(l.remove(a,["jimu-icon-btn","popup-menu-button"]),l.add(a,["feature-action","icon-operation"]));this.operationsDropMenu.btnNode&&this.own(n(this.operationsDropMenu.btnNode,"click",m.hitch(this,this._onLayerListOperationsClick)));this.own(n(this.operationsDropMenu,"onMenuClick",
m.hitch(this,this._onOperationsMenuItemClick)))},_onLayerListOperationsClick:function(){this._hideCurrentPopupMenu()},_onOperationsMenuItemClick:function(a){switch(a.key){case "turnAllLayersOn":this.turnAllRootLayers(!0);break;case "turnAllLayersOff":this.turnAllRootLayers(!1);break;case "expandAllLayers":this.foldOrUnfoldAllRootLayers(!1);break;case "collapseAlllayers":this.foldOrUnfoldAllRootLayers(!0)}},isFirstDisplayedLayerInfo:function(a){var b,c;a.isFirst||!a.isRootLayer()?b=!0:(b=this._getMovedSteps(a,
"moveup"),c=this.operLayerInfos.getLayerInfoArray(),a=this.operLayerInfos._getTopLayerInfoIndexById(a.id),b=this.isLayerHiddenInWidget(c[a-b])?!0:!1);return b},isLastDisplayedLayerInfo:function(a){var b,c;a.isLast||!a.isRootLayer()?b=!0:(b=this._getMovedSteps(a,"movedown"),c=this.operLayerInfos.getLayerInfoArray(),a=this.operLayerInfos._getTopLayerInfoIndexById(a.id),b=this.isLayerHiddenInWidget(c[a+b])?!0:!1);return b},moveUpLayer:function(a){var b=this._getMovedSteps(a,"moveup");this.layerListWidget._denyLayerInfosReorderResponseOneTime=
!0;(b=this.operLayerInfos.moveUpLayer(a,b))&&this._exchangeLayerTrNode(b,a)},moveDownLayer:function(a){var b=this._getMovedSteps(a,"movedown");this.layerListWidget._denyLayerInfosReorderResponseOneTime=!0;(b=this.operLayerInfos.moveDownLayer(a,b))&&this._exchangeLayerTrNode(a,b)},isLayerHiddenInWidget:function(a){var b=!1,c=a;if(a&&this.config.layerOptions&&void 0!==this.config.layerOptions[a.id])for(;c&&!(b=b||!this.config.layerOptions[c.id].display);)c=c.parentLayerInfo;else b=!1;return b},turnAllRootLayers:function(a){var b=
this.operLayerInfos.getLayerInfoArray();k.forEach(b,function(b){this.isLayerHiddenInWidget(b)||b.setTopLayerVisible(a)},this)},turnAllSameLevelLayers:function(a,b){var c={},e=a.getRootLayerInfo();e.traversal(m.hitch(this,function(d){d.parentLayerInfo&&d.parentLayerInfo.id===a.parentLayerInfo.id&&!this.isLayerHiddenInWidget(d)?c[d.id]={visible:b}:c[d.id]={visible:d.isVisible()}}));e.resetLayerObjectVisibility(c)},foldOrUnfoldAllRootLayers:function(a){var b=k.filter(this.operLayerInfos.getLayerInfoArray(),
function(a){return!this.isLayerHiddenInWidget(a)},this);this._foldOrUnfoldLayers(b,a)},foldOrUnfoldSameLevelLayers:function(a,b){var c;a.parentLayerInfo&&(c=k.filter(a.parentLayerInfo.getSubLayers(),function(a){return!this.isLayerHiddenInWidget(a)},this),this._foldOrUnfoldLayers(c,b))}})});